name: cetak_struk
description: "A new Flutter project."
publish_to: 'none'

version: 0.2.0+4

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_text_recognition: ^0.17.1
  path_provider: ^2.1.5
  share_plus: ^13.3.0
  cupertino_icons: ^2.0.0
  shared_preferences: ^2.5.5
  provider: ^6.1.2

  blue_thermal_printer: any
  package_info_plus: ^10.2.1
  flutter_markdown_plus: ^1.0.12
  flex_color_picker: ^4.0.0
  url_launcher: ^6.3.2
dependency_overrides:
  blue_thermal_printer:
    path: packages/blue_thermal_printer

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.1
  flutter_lints: ^6.0.0

flutter_native_splash:
  color: "#511d66"
  image: assets/icon/splash_icon.png

  android_12:
    image: assets/icon/splash_icon.png
    color: "#511d66"

  android: true
  ios: false
  web: false
  fullscreen: true
  android_gravity: center
  ios_content_mode: center

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#511d66"
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - brand.txt
    - assets/legal/
